trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

variables:
  # Pipeline variables
  - name: dockerHubUsername
    value: 'aravasaikrishna'    # Your Docker Hub username
  - name: imageRepository
    value: 'food-delivery'

pool:
  vmImage: 'ubuntu-latest'
  demands:
    - Agent.Name -equals Azure Pipelines

jobs:
- job: Build
  displayName: Build and Push Docker Images
  steps:
  - task: Docker@2
    displayName: Build and push backend image
    inputs:
      command: buildAndPush
      containerRegistry: 'food-delivery-docker-hub'
      repository: $(dockerHubUsername)/$(imageRepository)-backend
      dockerfile: $(Build.SourcesDirectory)/FoodDelivery/backend/Dockerfile
      tags: |
        $(Build.BuildId)
        latest
  
  - task: Docker@2
    displayName: Build and push frontend image
    inputs:
      command: buildAndPush
      containerRegistry: 'food-delivery-docker-hub'
      repository: $(dockerHubUsername)/$(imageRepository)-frontend
      dockerfile: $(Build.SourcesDirectory)/FoodDelivery/frontend/Dockerfile
      tags: |
        $(Build.BuildId)
        latest