trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'

variables:
  # Pipeline variables
  - name: dockerHubUsername
    value: 'aravasaikrishna'    # Your Docker Hub username
  - name: imageRepository
    value: 'food-delivery'
  - name: k8sNamespace
    value: 'food-delivery'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
    - job: Build
      displayName: Build
      steps:
      - task: Docker@2
        displayName: Build and push backend image
        inputs:
          command: buildAndPush
          containerRegistry: 'food-delivery-docker-hub'
          repository: $(dockerHubUsername)/$(imageRepository)-backend
          dockerfile: $(Build.SourcesDirectory)/FoodDelivery/backend/Dockerfile
          tags: |
            $(Build.BuildId)
            latest
      
      - task: Docker@2
        displayName: Build and push frontend image
        inputs:
          command: buildAndPush
          containerRegistry: 'food-delivery-docker-hub'
          repository: $(dockerHubUsername)/$(imageRepository)-frontend
          dockerfile: $(Build.SourcesDirectory)/FoodDelivery/frontend/Dockerfile
          tags: |
            $(Build.BuildId)
            latest

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: Deploy
      displayName: Deploy to AKS
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              displayName: Create namespace
              inputs:
                action: createNamespace
                namespace: $(k8sNamespace)

            - task: KubernetesManifest@0
              displayName: Deploy ConfigMap and Secrets
              inputs:
                action: deploy
                namespace: $(k8sNamespace)
                manifests: |
                  $(Build.SourcesDirectory)/k8s/backend-config.yaml
                  $(Build.SourcesDirectory)/k8s/backend-secrets.yaml
                
            - task: KubernetesManifest@0
              displayName: Deploy to AKS
              inputs:
                action: deploy
                namespace: $(k8sNamespace)
                manifests: |
                  $(Build.SourcesDirectory)/k8s/backend-deployment.yaml
                  $(Build.SourcesDirectory)/k8s/frontend-deployment.yaml
                  $(Build.SourcesDirectory)/k8s/backend-service.yaml
                  $(Build.SourcesDirectory)/k8s/frontend-service.yaml
                containers: |
                  $(dockerHubUsername)/$(imageRepository)-backend:$(Build.BuildId)
                  $(dockerHubUsername)/$(imageRepository)-frontend:$(Build.BuildId)