apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-backend
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery-backend
  template:
    metadata:
      labels:
        app: food-delivery-backend
    spec:
      containers:
      - name: food-delivery-backend
        image: fooddelivery.azurecr.io/food-delivery-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/fooddelivery"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: stripe-secret-key
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: email
        - name: PASSWORD_APP_EMAIL
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: password-app-email
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: twilio-auth-token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: food-delivery-secrets
              key: twilio-phone-number
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: food-delivery-backend
  namespace: food-delivery
spec:
  selector:
    app: food-delivery-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP 