apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-frontend
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery-frontend
  template:
    metadata:
      labels:
        app: food-delivery-frontend
    spec:
      containers:
      - name: food-delivery-frontend
        image: fooddelivery.azurecr.io/food-delivery-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://food-delivery-backend:4000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: food-delivery-frontend
  namespace: food-delivery
spec:
  selector:
    app: food-delivery-frontend
  ports:
  - port: 80
    targetPort: 5173
  type: LoadBalancer 